"""Crear tablas iniciales

Revision ID: 7bbd794a88e4
Revises: 
Create Date: 2026-03-09 18:13:05.717534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bbd794a88e4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.Column('codigo_postal', sa.String(), nullable=True),
    sa.Column('limite_velocidad', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zones_id'), 'zones', ['id'], unique=False)
    op.create_table('scooters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_serie', sa.String(), nullable=True),
    sa.Column('modelo', sa.String(), nullable=True),
    sa.Column('bateria', sa.Integer(), nullable=True),
    sa.Column('estado', sa.Enum('disponible', 'en_uso', 'mantenimiento', 'sin_bateria', name='scooterstatus'), nullable=True),
    sa.Column('zona_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['zona_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scooters_id'), 'scooters', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scooters_id'), table_name='scooters')
    op.drop_table('scooters')
    op.drop_index(op.f('ix_zones_id'), table_name='zones')
    op.drop_table('zones')
    # ### end Alembic commands ###
