"""añadir puntuacion_usuario

Revision ID: cf39b25f2122
Revises: 7bbd794a88e4
Create Date: 2026-03-09 18:13:28.247530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf39b25f2122'
down_revision: Union[str, Sequence[str], None] = '7bbd794a88e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scooters', sa.Column('puntuacion_usuario', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scooters', 'puntuacion_usuario')
    # ### end Alembic commands ###
